name: Build with Conan Toolchain

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies for Conan
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel build-essential

    - name: Install Conan
      run: pip3 install "conan==2.0.0" "pyyaml<=6.0"

    - name: Create Conan Default Profile
      run: |
        conan profile detect
        conan profile update settings.compiler.version=12 default

    - name: Cache Conan Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan

    - name: Create Toolchain Package
      run: |
        cd toolchain
        conan create . --name=toolchain --version=1.0 --user=user --channel=testing \
          -s compiler=gcc -s compiler.version=12 -s compiler.libcxx=libstdc++11

    - name: Install Dependencies and Build
      run: |
        mkdir -p build
        cd build
        conan install .. --profile ../profiles/gcc_profile
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
