name: Build with Conan Toolchain

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Build Essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev

    - name: Install Conan
      run: pip install conan==2.0.0

    - name: Cache Conan Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan

    - name: Detect Conan Profile
      run: conan profile detect --force

    - name: Create Toolchain Package
      run: |
        cd toolchain
        conan create . --name=toolchain --version=1.0 --user=user --channel=testing

    - name: Install Dependencies and Build
      run: |
        mkdir -p build
        cd build
        conan install .. --profile ../profiles/gcc_profile
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
