# GitHub Actions pipeline configuration
name: Build and Test Conan Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip3 install --upgrade pip setuptools wheel cython
        pip3 install "conan==2.0.0" "pyyaml<=6.0"

    - name: Run Conan Install
      run: |
        conan profile detect
        conan install . --build=missing

    - name: Build Project
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
