# GitHub Actions pipeline configuration
name: Build with Conan Toolchain

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Conan and Dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel cython
        pip install "conan==2.0.0" "pyyaml<=6.0"

    - name: Create Conan Default Profile
      run: |
        source venv/bin/activate
        conan profile detect --force
        conan profile update settings.compiler=gcc default
        conan profile update settings.compiler.version=10 default
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Cache Conan Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan

    - name: Create Toolchain Package
      run: |
        source venv/bin/activate
        cd toolchain
        conan create . --name=toolchain --version=1.0 --user=user --channel=testing --profile default

    - name: Install Dependencies and Build
      run: |
        source venv/bin/activate
        mkdir -p build
        cd build
        conan install .. --profile ../profiles/gcc_profile
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
